AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Spring API en VocLabs usando VPC existente

Parameters:
  ContainerImage:
    Type: String
    Default: "530225934111.dkr.ecr.us-west-2.amazonaws.com/spring-api:latest"
  ContainerPort:
    Type: Number
    Default: 8080
  ECSClusterName:
    Type: String
    Default: spring-cluster

Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to Fargate container
      VpcId: vpc-031edf9672a4fea40
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: vpc-031edf9672a4fea40
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: spring-alb
      Subnets:
        - subnet-00109aacacade5ab8
        - subnet-025aa338031ca9189
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: spring-target-group
      Port: 8080
      Protocol: HTTP
      VpcId: vpc-031edf9672a4fea40
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPort: "traffic-port"
      HealthCheckPath: "/"

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !GetAtt ALB.LoadBalancerArn
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName

  ECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: spring-api
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::530225934111:role/LabRole
      ContainerDefinitions:
        - Name: spring-api
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: spring-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTask
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-015552a54a4d40c4a
            - subnet-0145c3071dac15d1f
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: spring-api
          ContainerPort: !Ref ContainerPort

Outputs:
  ALBEndpoint:
    Description: "URL del ALB para acceder a la API"
    Value: !GetAtt ALB.DNSName